package org.joseph.friendsync.util

const val STATIC_ROOT = "static/"
const val POST_IMAGE_DIRECTORY = "post_pictures/"
const val POST_IMAGE_PATH = "$STATIC_ROOT/$POST_IMAGE_DIRECTORY"
const val EXTERNAL_POST_IMAGE_PATH = "/images"
const val USER_ID_PARAM = "user_id"
const val FOLLOWING_ID_PARAM = "following_id"
const val POST_ID_PARAM = "post_id"
const val PAGE_SIZE_PARAM = "page_size"
const val CATEGORY_ID_PARAM = "category_id"
const val COMMENTS_ID_PARAM = "comments_id"
const val CATEGORY_NAME_PARAM = "category_name"
const val LIKE_PARAM = "/like"
const val UNLIKE_PARAM = "/unlike"
const val PAGE_PARAM = "page"
const val QUERY_PARAM = "query"
const val IMAGE_PARAM_NAME = "image"
const val MESSAGE_PARAM_NAME = "message"
const val SEARCH_REQUEST_PATCH = "/search"
const val LIST_REQUEST_PATCH = "/list"
const val DELETE_REQUEST_PATCH = "/delete"
const val ADD_REQUEST_PATCH = "/add"
const val EDIT_REQUEST_PATCH = "/edit"
